export const LOAD_VAULTS = "LOAD_VAULTS";
export const LOAD_VAULTS_SUCCESS = "LOAD_VAULTS_SUCCESS";
export const LOAD_VAULTS_FAILURE = "LOAD_VAULTS_FAILURE";

export const COMMIT_VAULTS_CACHE = "COMMIT_VAULTS_CACHE";

export const REFRESH_VAULT = "REFRESH_VAULT";
export const PERIODIC_UPDATE = "PERIODIC_UPDATE";
export const APPROVAL_SUCCESS = "APPROVAL_SUCCESS";
